package com.sqleditor.service;
import com.sqleditor.model.ConnectionRequest; import com.sqleditor.security.*; import com.zaxxer.hikari.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import java.security.SecureRandom; import java.sql.*; import java.time.*; import java.util.*; import java.util.concurrent.*;
@Service public class ConnectionSessionService {
 private final JdbcTemplate db; private final CredentialCipher cipher; private final TokenHasher hasher; private final int minutes; private final SecureRandom random=new SecureRandom(); private final ConcurrentMap<String,HikariDataSource> pools=new ConcurrentHashMap<>();
 public ConnectionSessionService(JdbcTemplate db,CredentialCipher c,TokenHasher h,@Value("${app.connection.session-minutes}") int m){this.db=db;cipher=c;hasher=h;minutes=m;}
 public String create(String user,ConnectionRequest r){String token=token();String h=hasher.hash(token);CredentialCipher.Encrypted e=cipher.encrypt(r.getPassword());db.update("insert into connection_sessions(id,user_id,token_hash,db_type,host,port,database_name,db_username,password_ciphertext,password_iv,expires_at) values(?,?,?,?,?,?,?,?,?,?,?)",UUID.randomUUID().toString(),user,h,r.getDbType().toUpperCase(),r.getHost(),r.getPort(),r.getDatabase(),r.getUsername(),e.ciphertext(),e.iv(),Timestamp.from(Instant.now().plus(Duration.ofMinutes(minutes))));return token;}
 public Connection get(String user,String token)throws SQLException {String h=hasher.hash(token); List<Stored> rows=db.query("select db_type,host,port,database_name,db_username,password_ciphertext,password_iv from connection_sessions where user_id=? and token_hash=? and expires_at>current_timestamp",(rs,n)->new Stored(rs.getString(1),rs.getString(2),rs.getInt(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)),user,h);if(rows.isEmpty())throw new SecurityException("Bağlantı oturumu bulunamadı veya süresi doldu.");Stored s=rows.get(0);HikariDataSource pool=pools.computeIfAbsent(h,k->pool(s));return pool.getConnection();}
 public void close(String user,String token){String h=hasher.hash(token);db.update("delete from connection_sessions where user_id=? and token_hash=?",user,h);HikariDataSource p=pools.remove(h);if(p!=null)p.close();}
 public void history(String user,ConnectionRequest r){db.update("insert into connection_history(id,user_id,connection_name,db_type,host,port,database_name,db_username) values(?,?,?,?,?,?,?,?)",UUID.randomUUID().toString(),user,blank(r.getConnectionName()),r.getDbType().toUpperCase(),r.getHost(),r.getPort(),r.getDatabase(),r.getUsername());}
 private HikariDataSource pool(Stored s){HikariConfig c=new HikariConfig();c.setJdbcUrl(url(s));c.setUsername(s.username);c.setPassword(cipher.decrypt(s.ciphertext,s.iv));c.setMaximumPoolSize(3);c.setMinimumIdle(0);c.setConnectionTimeout(10_000);c.setValidationTimeout(3_000);c.setMaxLifetime(30*60_000L);c.setPoolName("target-db-pool");return new HikariDataSource(c);}
 private String url(Stored s){return switch(s.type){case "MYSQL"->"jdbc:mysql://"+s.host+":"+s.port+"/"+s.database+"?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Istanbul&characterEncoding=UTF-8";case "POSTGRESQL"->"jdbc:postgresql://"+s.host+":"+s.port+"/"+s.database;case "MSSQL"->"jdbc:sqlserver://"+s.host+":"+s.port+";databaseName="+s.database+";encrypt=true";default->throw new IllegalArgumentException("Desteklenmeyen veritabanı tipi");};} private String token(){byte[] b=new byte[32];random.nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b);} private String blank(String v){return v==null||v.isBlank()?null:v.trim();} private record Stored(String type,String host,int port,String database,String username,String ciphertext,String iv){}
}
